### ISSUE TITLE
1612001 - Hoàng Dân An

### ISSUE THREAD

**Issue by beohoang98** [nghiaplt/DataScienceFinalProject#2]
Chào bạn, về phần câu hỏi -> trả lời và dữ liệu mình thấy nhóm bạn làm đầy đủ và gần gũi thực tế. :100:

Tuy nhiên về phần xử lý để ra output, mình cũng có một số câu hỏi là:
- Có một số yếu tố nằm ngoài dữ liệu có được (VD: công nghệ của năm SX, xu hướng của năm SX, ....), thì nó có ảnh hưởng như thế nào đến KQ kết luận từ dữ liệu mình đang có, hoặc, dữ liệu mình đang có có những field nào thể hiện điều đó?
- Trong phần dữ liệu có yếu tố nhiễu hay không và cách giải quyết như thế nào? VD: giá thu nhập được không phải là giá chính xác mà là giá đã giảm (hoặc xả kho) của riêng fpt.com ....

**Comment by nghiaplt** [comment]
Cám ơn bạn đã góp ý nhóm mình. Hiện tại nhóm mình đang đổi đề tài khác, vì nhóm không thấy được ứng dụng từ đề tài trước. Đề tài mới của nhóm mình về việc phân loại cảm úc dựa trên văn bản.
