### ISSUE TITLE
1612001 - Final

### ISSUE THREAD

**Issue by beohoang98** [nghiaplt/DataScienceFinalProject#3]
- **Góc Khen**: 
   + Nội dung và ứng dụng bài toán của bạn rất hay
   + Annotation bằng tay tất cả 12k comment ???

- **Góp ý nhỏ**:
   + Phần `distplot` để visualize các feature `count_words`, `count_capital`, .... của bạn mình nghĩ ở mỗi feature nên gộp chung happy, sad, angry, neutral vào 1 chart để có thể thấy được khác biệt về số lượng và shape của đồ thị hơn, để riêng 4 cái nhìn thấy hao hao khó thấy được sự khác biệt

   + Hình như tập X_train split ra từ X (và cả X) bạn chưa `drop` ra cột nhãn (`emotion`, `emotion_label`) thì phải, vậy thuật toán nó có đọc cái đó không ?

**Comment by nghiaplt** [comment]
Cám ơn bạn đã nhận xét nhóm. Vì tụi mình cũng có viết Tool hỗ trợ quá trình annotate, nên trung bình mỗi 15p một người annotate được ~200 comment. Nên 2 người annotate khoảng tầm 3 ngày là xong.

Đúng là phần `displot` mình thấy cũng khá rối, cám ơn bạn đã góp ý. Nên có một chart để tổng hợp lại tất cả !!

Về lúc chạy sẽ không ảnh hưởng đến logic của các bước trong pipeline (vì nhóm mình không đọc 2 cột đó), nhưng để 2 cột đó trong quá trình train sẽ dư, cũng có thể tăng memory trong lúc train.
